const ProjectApi = [
    {
        Id: 1,
        ProjectName: "JobFinder",
        ProjectDescription: "JobFindr mobile application, It aims to simplify the job search process and provide valuable job information to users. The app integrates with the Jsearch API from Rapid API to fetch job listings from various sources.",
        firstImg: "JobFinder/jobfinder1.jpg",
        githubUrl: "https://github.com/vishal-sawai/JobFinder",
        liveUrl: "",
        slides: [
            { url: "/assets/project media/JobFinder/jobfinder1.jpg", title: "JobFinder" },
            { url: "/assets/project media/JobFinder/jobFinder.mp4", title: "video" },
            { url: "/assets/project media/JobFinder/jobfinder2.jpg", title: "Sign In | Welcome | Sign Up" },
            { url: "/assets/project media/JobFinder/jobfinder3.jpg", title: "Menu | Profile | Saved Jobs" },
            { url: "/assets/project media/JobFinder/jobfinder4.jpg", title: "Home | Search | Job Details" },

        ],
        Type: "Mobile App",
        TechStack: ["React Native", "Rapid Api", "Firebase"],
    },
    {
        Id: 2,
        ProjectName: "Tesla Website",
        ProjectDescription: "Tesla Website clone",
        firstImg: "Tesla Web/tesla1.png",
        githubUrl: "https://github.com/vishal-sawai/tesla-clone",
        liveUrl: "https://vishal-sawai.github.io/tesla-clone/",
        slides: [
            { url: "/assets/project media/Tesla Web/tesla1.png", title: "Home" },
            { url: "/assets/project media/Tesla Web/tesla2.png", title: "Model 3" },
            { url: "/assets/project media/Tesla Web/tesla3.png", title: "Model Y" },
            { url: "/assets/project media/Tesla Web/tesla4.png", title: "Model S" },
            { url: "/assets/project media/Tesla Web/tesla5.png", title: "Model X" },
            { url: "/assets/project media/Tesla Web/tesla6.png", title: "Solar panels" },
            { url: "/assets/project media/Tesla Web/tesla7.png", title: "Solar Roof" },
            { url: "/assets/project media/Tesla Web/tesla8.png", title: "Powerwall" },
            { url: "/assets/project media/Tesla Web/tesla9.png", title: "Accessories" },
            { url: "/assets/project media/Tesla Web/tesla10.png", title: "Menu" },
        ],
        Type: "WebApp",
        TechStack: ["React Js", "Redux", "CSS"],
    },
    {
        Id: 3,
        ProjectName: "Helping Hand",
        ProjectDescription: "Helping hand is a fundraising web platform is an online platform that connects individuals and organizations with potential donors to raise funds for various causes, such as charitable donations, medical expenses, educational expenses, and more. ",
        firstImg: "Helping Hand/1.png",
        githubUrl: "https://github.com/vishal-sawai/Fundraising",
        liveUrl: "",
        slides: [
            { url: "/assets/project media/Helping Hand/Helping hand.mp4", title: "video" },
            { url: "/assets/project media/Helping Hand/1.png", title: "Home" },
            { url: "/assets/project media/Helping Hand/2.png", title: "Campaign" },
            { url: "/assets/project media/Helping Hand/3.png", title: "Causes" },
            { url: "/assets/project media/Helping Hand/4.png", title: "Campaign Request Form" },
            { url: "/assets/project media/Helping Hand/5.png", title: "Donation Form" },
            { url: "/assets/project media/Helping Hand/6.png", title: "RazorPay Payment" },
            { url: "/assets/project media/Helping Hand/7.png", title: "Thank You" },
            { url: "/assets/project media/Helping Hand/8.png", title: "About Us" },
            { url: "/assets/project media/Helping Hand/9.png", title: "Admin Login" },
            { url: "/assets/project media/Helping Hand/10.png", title: "Dashboard" },
            { url: "/assets/project media/Helping Hand/11.png", title: "Donation" },
            { url: "/assets/project media/Helping Hand/12.png", title: "Campaingn" },
        ],
        Type: "WebApp",
        TechStack: ["Tailwind CSS", "JS", "Django", "MySql", "Razor Pay"],
    },
    {
        Id: 4,
        ProjectName: "CNMS",
        ProjectDescription: "College Notes Management System is provide an organized platform for teachers to store, manage, and distribute their class notes to students in an efficient and secure manner.With the CNMS, teachers can upload class notes, slides, and other educational materials, and students can easily access and download the materials. ",
        firstImg: "CNMS/1.png",
        githubUrl: "https://github.com/vishal-sawai/CNMSeclispe",
        liveUrl: "",
        slides: [
            { url: "/assets/project media/CNMS/CNMS.mp4", title: "video" },
            { url: "/assets/project media/CNMS/1.png", title: "Home" },
            { url: "/assets/project media/CNMS/2.png", title: "Course & About" },
            { url: "/assets/project media/CNMS/3.png", title: "Contact Us" },
            { url: "/assets/project media/CNMS/4.png", title: "User Login" },
            { url: "/assets/project media/CNMS/5.png", title: "Admin Login" },
            { url: "/assets/project media/CNMS/6.png", title: "Dashboard" },
            { url: "/assets/project media/CNMS/7.png", title: "Message" },
            { url: "/assets/project media/CNMS/8.png", title: "Add Student" },
            { url: "/assets/project media/CNMS/9.png", title: "Add Teacher" },
            { url: "/assets/project media/CNMS/10.png", title: "Add Notes" },
            { url: "/assets/project media/CNMS/11.png", title: "Authentication Mail" },
            { url: "/assets/project media/CNMS/12.png", title: "Notes" },
        ],
        Type: "WebApp",
        TechStack: ["Tailwind CSS ", "JS", "JAVA (JSP/Servlet) ", " MySql"],
    },
    {
        Id: 5,
        ProjectName: "Open Code",
        ProjectDescription: "Open Code is a web application that provides web development, app development and graphics design services to clients ",
        firstImg: "Open Code/1.png",
        githubUrl: "",
        liveUrl: "",
        slides: [
            { url: "/assets/project media/Open Code/open code.mp4", title: "video" },
            { url: "/assets/project media/Open Code/1.png", title: "Home" },
            { url: "/assets/project media/Open Code/2.png", title: "About Us" },
            { url: "/assets/project media/Open Code/3.png", title: "Our Services" },
            { url: "/assets/project media/Open Code/4.png", title: "Our Services" },
            { url: "/assets/project media/Open Code/5.png", title: "Web Development Services" },
            { url: "/assets/project media/Open Code/6.png", title: "Enquire Form" },
            { url: "/assets/project media/Open Code/7.png", title: "Contact Us" },
            { url: "/assets/project media/Open Code/8.png", title: "Admin Login" },
        ],
        Type: "WebApp",
        TechStack: ["Bootstrap", " JS", "PHP", "MySql"],
    },
    {
        Id: 6,
        ProjectName: "RJ Hostel",
        ProjectDescription: "Admin portal, Student portal, Auto receipt, Payment integration, Payment history ,online support",
        firstImg: "RJ Hostel/rj1.png",
        githubUrl: "",
        liveUrl: "",
        slides: [
            { url: "/assets/project media/RJ Hostel/rj1.png", title: "Home" },
            { url: "/assets/project media/RJ Hostel/rj2.png", title: "About Us" },
            { url: "/assets/project media/RJ Hostel/rj3.png", title: "Call Request Form" },
            { url: "/assets/project media/RJ Hostel/rj4.png", title: "Testimonial" },
            { url: "/assets/project media/RJ Hostel/rj5.png", title: "Contact Us" },
            { url: "/assets/project media/RJ Hostel/rj6.png", title: "Rooms" },
            { url: "/assets/project media/RJ Hostel/rj7.png", title: "Rooms Details" },
            { url: "/assets/project media/RJ Hostel/rj8.png", title: "Admin Login" },
            { url: "/assets/project media/RJ Hostel/rj9.png", title: "Testimonial Admin Side" },
            { url: "/assets/project media/RJ Hostel/rj10.png", title: "Students" },
            { url: "/assets/project media/RJ Hostel/rj11.png", title: "Add Student" },
            { url: "/assets/project media/RJ Hostel/rj12.png", title: "Login Details Email" },
            { url: "/assets/project media/RJ Hostel/rj13.png", title: "Student Information" },
            { url: "/assets/project media/RJ Hostel/rj14.png", title: "Add Payment Form" },
            { url: "/assets/project media/RJ Hostel/rj15.png", title: "Term & Condition Details" },
            { url: "/assets/project media/RJ Hostel/rj16.png", title: "Student Payment" },
            { url: "/assets/project media/RJ Hostel/rj17.png", title: "Razor Payment" },
            { url: "/assets/project media/RJ Hostel/rj18.png", title: "Thank You" },
            { url: "/assets/project media/RJ Hostel/rj19.png", title: "Payment History" },
            { url: "/assets/project media/RJ Hostel/rj20.png", title: "Payment Invoice" },
            { url: "/assets/project media/RJ Hostel/rj21.png", title: "Order Discount" },
        ],
        Type: "WebApp",
        TechStack: ["Bootstrap", " JS", "PHP", " MySql", "Razor Pay"],
    }

];

export default ProjectApi;